export const ADMINACTIVITY_TYPE_ALL = '000000';

// 로그인
export const ADMINACTIVITY_TYPE_AUTH_LOGIN = '010101';
export const ADMINACTIVITY_TYPE_AUTH_LOGOUT = '010102';

// 계정 관련
export const ADMINACTIVITY_TYPE_ACCOUNT_VIEWLIST = '020101';
export const ADMINACTIVITY_TYPE_ACCOUNT_NEW = '020102';
export const ADMINACTIVITY_TYPE_ACCOUNT_CHANGEACL = '020103';
export const ADMINACTIVITY_TYPE_ACCOUNT_ACTIVATION = '020104';
export const ADMINACTIVITY_TYPE_ACCOUNT_DELETE = '020105';
export const ADMINACTIVITY_TYPE_ACCOUNT_CHANGEPW = '020106';

// 유저 관련
export const ADMINACTIVITY_TYPE_USER_VIEWLIST = '030101';
export const ADMINACTIVITY_TYPE_USER_VIEWDETAIL = '030102';
export const ADMINACTIVITY_TYPE_USER_ADDTOBLACKLIST = '030103';
export const ADMINACTIVITY_TYPE_USER_RELEASEFROMBLACKLIST = '030104';
export const ADMINACTIVITY_TYPE_USER_UPDATE = '030105';
export const ADMINACTIVITY_TYPE_USER_ACTLOG_VIEWLIST = '030106';
export const ADMINACTIVITY_TYPE_USER_PAYLOG_VIEWLIST = '030107';
export const ADMINACTIVITY_TYPE_USER_REWARDTOUSERGROUP = '030108';

// 공지사항 관련
export const ADMINACTIVITY_TYPE_NOTIFICATION_VIEWLIST = '040101';
export const ADMINACTIVITY_TYPE_NOTIFICATION_NEW = '040102';
export const ADMINACTIVITY_TYPE_NOTIFICATION_UPDATE = '040103';
export const ADMINACTIVITY_TYPE_NOTIFICATION_DELETE = '040104';
export const ADMINACTIVITY_TYPE_NOTIFICATION_ACTIVATION = '040105';

// 우편함/푸쉬알람 메세지 관련
export const ADMINACTIVITY_TYPE_MESSAGE_VIEWLIST = '050101';
export const ADMINACTIVITY_TYPE_MESSAGE_SEND = '050102';
export const ADMINACTIVITY_TYPE_MESSAGE_UPDATE = '050103';
export const ADMINACTIVITY_TYPE_MESSAGE_DELETE = '050104';
export const ADMINACTIVITY_TYPE_LANGPRESET_ADD = '050106';
export const ADMINACTIVITY_TYPE_LANGPRESET_UPDATE = '050107';
export const ADMINACTIVITY_TYPE_LANGPRESET_DELETE = '050108';
export const ADMINACTIVITY_TYPE_REWARDPRESET_ADD = '050109';
export const ADMINACTIVITY_TYPE_REWARDPRESET_UPDATE = '050110';
export const ADMINACTIVITY_TYPE_REWARDPRESET_DELETE = '050111';

// 이벤트 관련
export const ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_VIEWLIST = '060101';
export const ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_NEW = '060102';
export const ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_UPDATE = '060103';
export const ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_DELETE = '060104';
export const ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_ACTIVATION = '060105';
export const ADMINACTIVITY_TYPE_EVENT_COUPON_VIEWLIST = '060110';
export const ADMINACTIVITY_TYPE_EVENT_COUPON_NEW = '060111';

// 활동로그/시스템로그 관련
export const ADMINACTIVITY_TYPE_ACTIVITYLOG_VIEWLIST = '070101';
export const ADMINACTIVITY_TYPE_SYSTEMLOG_VIEWLIST = '070201';

// 도구사용 관련
export const ADMINACTIVITY_TYPE_TOOL_UPDATEARENATABLE = '080101';
export const ADMINACTIVITY_TYPE_TOOL_REGISTERSEASONTOMARKET = '080102';
export const ADMINACTIVITY_TYPE_TOOL_REGISTERNFTTOMARKET = '080103';
export const ADMINACTIVITY_TYPE_TOOL_UPDATEDOWNLOADURL = '080104';
export const ADMINACTIVITY_TYPE_TOOL_UPDATEMAINTENANCEINFO = '080105';

// 환경설정 관련
export const ADMINACTIVITY_TYPE_SETTING_VIEWLIST = '090101';
export const ADMINACTIVITY_TYPE_SETTING_UPDATE = '090102';
export const ADMINACTIVITY_TYPE_SETTING_VIEWCLIENTCONFIG = '090301';
export const ADMINACTIVITY_TYPE_SETTING_UPDATECLIENTCONFIG = '090302';


// NFT 관련
export const ADMINACTIVITY_TYPE_NFT_CREATE = '100101';
export const ADMINACTIVITY_TYPE_NFT_UPLOADMETADATA = '100102';
export const ADMINACTIVITY_TYPE_NFT_MINT = '100103';
export const ADMINACTIVITY_TYPE_NFT_TRANSFER = '100104';
export const ADMINACTIVITY_TYPE_NFT_BURN = '100106';
export const ADMINACTIVITY_TYPE_NFT_UPDATEMETADATA = '100107';
export const ADMINACTIVITY_TYPE_WALLET_VIEWLIST = '100201';
export const ADMINACTIVITY_TYPE_WALLET_ADDNEW = '100202';
export const ADMINACTIVITY_TYPE_WALLET_UPDATE = '100203';
export const ADMINACTIVITY_TYPE_WALLET_DELETE = '100204';
export const ADMINACTIVITY_TYPE_TOKEN_TRANSFER = '100301';

// 마켓 관련
export const ADMINACTIVITY_TYPE_MARKET_BALANCE_VIEW = '110101';
export const ADMINACTIVITY_TYPE_MARKET_BALANCE_TRANSFER = '110102';


export const activityLogNameTable = new Map<string, string>();

// 로그인
activityLogNameTable.set(ADMINACTIVITY_TYPE_AUTH_LOGIN, '로그인');
activityLogNameTable.set(ADMINACTIVITY_TYPE_AUTH_LOGOUT, '로그아웃');

// 계정 관련
activityLogNameTable.set(ADMINACTIVITY_TYPE_ACCOUNT_NEW, '새 계정 생성');
activityLogNameTable.set(ADMINACTIVITY_TYPE_ACCOUNT_CHANGEACL, '계정 사용권한 변경');
activityLogNameTable.set(ADMINACTIVITY_TYPE_ACCOUNT_ACTIVATION, '계정 활성화/비활성화');
activityLogNameTable.set(ADMINACTIVITY_TYPE_ACCOUNT_DELETE, '계정 삭제');
activityLogNameTable.set(ADMINACTIVITY_TYPE_ACCOUNT_CHANGEPW, '계정 암호변경');

// 유저 관련
activityLogNameTable.set(ADMINACTIVITY_TYPE_USER_VIEWLIST, '유저목록 조회');
activityLogNameTable.set(ADMINACTIVITY_TYPE_USER_VIEWDETAIL, '유저 상세정보 조회');
activityLogNameTable.set(ADMINACTIVITY_TYPE_USER_ADDTOBLACKLIST, '블랙리스트에 등록');
activityLogNameTable.set(ADMINACTIVITY_TYPE_USER_RELEASEFROMBLACKLIST, '블랙리스트에서 해제');
activityLogNameTable.set(ADMINACTIVITY_TYPE_USER_UPDATE, '유저정보 변경');

// 공지사항 관련
activityLogNameTable.set(ADMINACTIVITY_TYPE_NOTIFICATION_NEW, '새 공지사항 생성');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NOTIFICATION_UPDATE, '공지사항 변경');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NOTIFICATION_DELETE, '공지사항 삭제');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NOTIFICATION_ACTIVATION, '공지사항 활성화/비활성화');

// 우편함/푸쉬알람 메세지 관련
activityLogNameTable.set(ADMINACTIVITY_TYPE_MESSAGE_VIEWLIST, '메세지 목록 조회');
activityLogNameTable.set(ADMINACTIVITY_TYPE_MESSAGE_SEND, '새 메세지 전송');
activityLogNameTable.set(ADMINACTIVITY_TYPE_MESSAGE_UPDATE, '예약 메세지 수정');
activityLogNameTable.set(ADMINACTIVITY_TYPE_MESSAGE_DELETE, '메세지 삭제');

// 이벤트 관련
activityLogNameTable.set(ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_VIEWLIST, '이벤트 목록 조회');
activityLogNameTable.set(ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_NEW, '새 이벤트 생성');
activityLogNameTable.set(ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_UPDATE, '이밴트 정보 변경');
activityLogNameTable.set(ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_DELETE, '이벤트 삭제');
activityLogNameTable.set(ADMINACTIVITY_TYPE_EVENT_LOGINREWARD_ACTIVATION, '이벤트 활성화/비활성화');

// 환경설정 관련
activityLogNameTable.set(ADMINACTIVITY_TYPE_SETTING_UPDATE, '환경설정 변경');

// NFT 관련
activityLogNameTable.set(ADMINACTIVITY_TYPE_NFT_CREATE, 'NFT 속성 생성');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NFT_UPLOADMETADATA, '메타데이터 S3 저장');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NFT_MINT, 'NFT 민팅');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NFT_TRANSFER, 'NFT 전송');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NFT_BURN, 'NFT 소각');
activityLogNameTable.set(ADMINACTIVITY_TYPE_NFT_UPDATEMETADATA, '메타데이터 업데이트');
activityLogNameTable.set(ADMINACTIVITY_TYPE_WALLET_VIEWLIST, '지갑 목록 조회');
activityLogNameTable.set(ADMINACTIVITY_TYPE_WALLET_ADDNEW, '새 지갑 추가');
activityLogNameTable.set(ADMINACTIVITY_TYPE_WALLET_UPDATE, '지갑정보 업데이터');
activityLogNameTable.set(ADMINACTIVITY_TYPE_WALLET_DELETE, '지갑 삭제');
activityLogNameTable.set(ADMINACTIVITY_TYPE_TOKEN_TRANSFER, 'ERC20 토큰 전송');
activityLogNameTable.set(ADMINACTIVITY_TYPE_MARKET_BALANCE_VIEW, '마켓 매출 조회');
activityLogNameTable.set(ADMINACTIVITY_TYPE_MARKET_BALANCE_TRANSFER, '마켓 매출 인출');